In [ ]:
pip install psutil


In [ ]:
import psutil
import os

# Get the current process ID
pid = os.getpid()

# Get the process object for the current process
process = psutil.Process(pid)

# Get the memory usage before running the algorithm
start_memory = process.memory_info().rss

# Run your algorithm here

# Get the memory usage after running the algorithm
end_memory = process.memory_info().rss

# Calculate the memory usage difference
memory_used = end_memory - start_memory
print("Memory used by algorithm: {:.2f} MB".format(memory_used / (1024 * 1024)))


Memory used by algorithm: 0.00 MB


In [ ]:
#Data prep
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.preprocessing import StandardScaler
# Scale the data
from sklearn.preprocessing import MinMaxScaler

from keras.layers import Input, LSTM, Bidirectional, Dense,Dropout
from keras.models import Sequential
from keras.layers import Dense, LSTM, Bidirectional
from keras.optimizers import Adam



input_file = "/content/Scenario1.csv"



x= pd.read_csv(input_file, usecols=[9,13,14,15,16,17,18])


y= pd.read_csv(input_file, usecols=[0 ,1,19])

x=x.dropna()
y=y.dropna()

train_percentage = 1


# Calculate the index to split the data
split_index = int(train_percentage * len(x))
#split_index=340    #a2e
#split_index=750    #a2i

x=x[:split_index]
y= y[:split_index]

scaler = MinMaxScaler(feature_range=(-1,1))
scaler1 = MinMaxScaler(feature_range=(-1,1))
x = scaler.fit_transform(x)
y = scaler1.fit_transform(y)











In [ ]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv(input_file, usecols=[9,13,14,15,16,17,18])


# Flip the column upside down


df['g1']= df['g1'][:split_index]
df.dropna(subset=['g1'], inplace=True)
df['g1']= df['g1'].values[::-1]*-1

df['g2']= df['g2'][:split_index]
df.dropna(subset=['g2'], inplace=True)
df['g2']= df['g2'].values[::-1]*-1

df['g3']= df['g3'][:split_index]
df.dropna(subset=['g3'], inplace=True)
df['g3']= df['g3'].values[::-1]*-1

df['T']= df['T'][:split_index]
df.dropna(subset=['T'], inplace=True)
df['T']= df['T'].values[::-1]

df['ax']= df['ax'][:split_index]
df.dropna(subset=['ax'], inplace=True)
df['ax']= df['ax'].values[::-1]

df['ay']= df['ay'][:split_index]
df.dropna(subset=['ay'], inplace=True)
df['ay']= df['ay'].values[::-1]

df['az']= df['az'][:split_index]
df.dropna(subset=['az'], inplace=True)
df['az']= df['az'].values[::-1]

# Save the DataFrame to a new CSV file
df.to_csv('XF.csv', index=False)


In [ ]:

#Single model training
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

from keras.layers import Input, LSTM, Bidirectional, Dense,Dropout
from keras.models import Sequential
from keras.layers import Dense, LSTM, Bidirectional
from keras.optimizers import Adam


input_file = "/content/Scenario1.csv"



x= pd.read_csv(input_file, usecols=[9,13,14,15,16,17,18])

y= pd.read_csv(input_file, usecols=[0 ,1,19])

x=x.dropna()
y=y.dropna()

scaler = MinMaxScaler(feature_range=(-1,1))
scaler1 = MinMaxScaler(feature_range=(-1,1))
x = scaler.fit_transform(x)
y = scaler1.fit_transform(y)



x=x[:split_index]
y= y[:split_index]


x= np.reshape(x, (x.shape[0], x.shape[1], 1))




# Build the bidirectional LSTM model
model = Sequential()

model.add(Bidirectional(LSTM(128, return_sequences=True), input_shape=(x.shape[1], 1)))
model.add(Dropout(0.1))


model.add(Bidirectional(LSTM(64, return_sequences=False)))

model.add(Dense(25, activation='relu'))  # Add a dense layer with ReLU activation
model.add(Dense(y_train.shape[1]))  # Output layer

# Compile the model

model.compile(optimizer='adam', loss='mean_squared_error')



import time

pid = os.getpid()

# Get the process object for the current process
process = psutil.Process(pid)

# Get the memory usage before running the algorithm
start_memory = process.memory_info().rss

# Run your algorithm here






# Start the timer
start_time = time.time()


# Train the model

model.fit(x, y, batch_size=1, epochs=10)


# Get the memory usage after running the algorithm
end_memory = process.memory_info().rss

# Calculate the memory usage difference
memory_used = end_memory - start_memory
print("Memory used by algorithm: {:.2f} MB".format(memory_used / (1024 * 1024)))

# Stop the timer
end_time = time.time()

# Calculate the training time
training_time = end_time - start_time
print("Training time: {:.2f} seconds".format(training_time))




Epoch 1/10
989/989 [==============================] - 29s 22ms/step - loss: 0.1673
Epoch 2/10
989/989 [==============================] - 25s 25ms/step - loss: 0.0859
Epoch 3/10
989/989 [==============================] - 19s 20ms/step - loss: 0.0503
Epoch 4/10
989/989 [==============================] - 21s 21ms/step - loss: 0.0444
Epoch 5/10
989/989 [==============================] - 19s 19ms/step - loss: 0.0394
Epoch 6/10
989/989 [==============================] - 19s 20ms/step - loss: 0.0361
Epoch 7/10
989/989 [==============================] - 19s 19ms/step - loss: 0.0344
Epoch 8/10
989/989 [==============================] - 21s 21ms/step - loss: 0.0308
Epoch 9/10
989/989 [==============================] - 19s 20ms/step - loss: 0.0275
Epoch 10/10
989/989 [==============================] - 19s 19ms/step - loss: 0.0268
Memory used by algorithm: 6.32 MB
Training time: 269.48 seconds
31/31 [==============================] - 2s 13ms/step
[[ -6.276317   -3.0265172   2.766283 ]
 [ -6.459841

In [ ]:
#Single model prediction
input_file1 = "/content/XF.csv"


xx= pd.read_csv(input_file1, usecols=[0,1,2,3,4,5,6])

xx=xx[:split_index]
xx=scaler.transform(xx)



xx= np.reshape(xx, (xx.shape[0], xx.shape[1], 1))

import time

# Start the timer
start_time = time.time()


predictionsall = model.predict(xx)


end_time = time.time()

# Calculate the training time
training_time = end_time - start_time
print("Prediction time: {:.2f} seconds".format(training_time))

predictionsall = scaler1.inverse_transform(predictionsall)

# Display predictions
print(predictionsall)



df3 = pd.DataFrame(predictionsall,columns=['x2', 'y2','z2'])

# Save the DataFrame to a CSV file
df3.to_csv('predictions_single.csv', index=False)

31/31 [==============================] - 0s 13ms/step
Prediction time: 0.69 seconds
[[-19.922596   91.363884    2.797609 ]
 [-19.640995   91.15564     2.7229762]
 [-18.89584    89.63701     2.6771307]
 ...
 [ -9.237589   -0.7999728   2.409741 ]
 [ -6.6650915  -3.4518335   2.6810572]
 [ -6.5530267  -2.4372478   2.7463398]]


In [ ]:
#Parallel model x training
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.preprocessing import StandardScaler
# Scale the data
from sklearn.preprocessing import MinMaxScaler

from keras.layers import Input, LSTM, Bidirectional, Dense,Dropout
from keras.models import Sequential
from keras.layers import Dense, LSTM, Bidirectional
from keras.optimizers import Adam


input_file = "/content/Scenario1.csv"




x1= pd.read_csv(input_file, usecols=[9,13,16])

y1= pd.read_csv(input_file, usecols=[0])

x1=x1.dropna()
y1=y1.dropna()

x1=x1[:split_index]
y1= y1[:split_index]

scalerx = MinMaxScaler(feature_range=(-1,1))
scaler1x = MinMaxScaler(feature_range=(-1,1))


x1 = scalerx.fit_transform(x1)
y1 = scaler1x.fit_transform(y1)


x1= np.reshape(x1, (x1.shape[0], x1.shape[1], 1))
# x_train.shape



# Build the bidirectional LSTM model
modelx = Sequential()
modelx.add(Bidirectional(LSTM(128, return_sequences=True), input_shape=(x1.shape[1], 1)))
modelx.add(Dropout(0.1))

modelx.add(Bidirectional(LSTM(64, return_sequences=False)))

modelx.add(Dense(25, activation='relu'))  # Add a dense layer with ReLU activation
modelx.add(Dense(y1.shape[1]))  # Output layer

# Compile the model
modelx.compile(optimizer='adam', loss='mean_squared_error')


import time

# Start the timer
start_time = time.time()


import psutil
import os

# Get the current process ID
pid = os.getpid()

# Get the process object for the current process
process = psutil.Process(pid)

# Get the memory usage before running the algorithm
start_memory = process.memory_info().rss

# Run your algorithm here



modelx.fit(x1, y1, batch_size=1, epochs=10)


# Get the memory usage after running the algorithm
end_memory = process.memory_info().rss

# Calculate the memory usage difference
memory_used = end_memory - start_memory
print("Memory used by algorithm: {:.2f} MB".format(memory_used / (1024 * 1024)))

end_time = time.time()

# Calculate the training time
training_time = end_time - start_time
print("Prediction time: {:.2f} seconds".format(training_time))



Epoch 1/10
989/989 [==============================] - 19s 12ms/step - loss: 0.3528
Epoch 2/10
989/989 [==============================] - 12s 12ms/step - loss: 0.1473
Epoch 3/10
989/989 [==============================] - 12s 13ms/step - loss: 0.0514
Epoch 4/10
989/989 [==============================] - 12s 12ms/step - loss: 0.0380
Epoch 5/10
989/989 [==============================] - 12s 12ms/step - loss: 0.0431
Epoch 6/10
989/989 [==============================] - 12s 12ms/step - loss: 0.0294
Epoch 7/10
989/989 [==============================] - 12s 12ms/step - loss: 0.0276
Epoch 8/10
989/989 [==============================] - 12s 12ms/step - loss: 0.0242
Epoch 9/10
989/989 [==============================] - 12s 12ms/step - loss: 0.0195
Epoch 10/10
989/989 [==============================] - 14s 14ms/step - loss: 0.0218
Memory used by algorithm: 83.07 MB
Prediction time: 148.12 seconds
31/31 [==============================] - 2s 14ms/step
[[-1.06979265e+01]
 [-1.09281588e+01]
 [-1.04788

In [ ]:
#Parallel model x prediction

input_file1 = "/content/XF.csv"


xfx= pd.read_csv(input_file1, usecols=[0,1,4])
xfx=xfx[:split_index]
xfx=scalerx.transform(xfx)



xfx= np.reshape(xfx, (xfx.shape[0], xfx.shape[1], 1))

import time

# Start the timer
start_time = time.time()



predictionsx = modelx.predict(xfx)

end_time = time.time()

# Calculate the training time
training_time = end_time - start_time
print("Prediction time: {:.2f} seconds".format(training_time))

# Inverse transform the predictions if using scaling
predictionsx = scaler1x.inverse_transform(predictionsx)

# Display predictions
print(predictionsx)

31/31 [==============================] - 0s 9ms/step
Prediction time: 0.42 seconds
[[-1.46264133e+01]
 [-1.50331612e+01]
 [-1.69121323e+01]
 [-1.49457321e+01]
 [-1.65003948e+01]
 [-1.50259495e+01]
 [-1.52648926e+01]
 [-1.56799393e+01]
 [-1.71297855e+01]
 [-1.60784435e+01]
 [-1.58566294e+01]
 [-1.56857433e+01]
 [-1.62575474e+01]
 [-1.58163643e+01]
 [-1.58499708e+01]
 [-1.78127003e+01]
 [-1.56283016e+01]
 [-1.58611155e+01]
 [-1.54019165e+01]
 [-1.86836777e+01]
 [-1.71268692e+01]
 [-1.80752640e+01]
 [-1.63823318e+01]
 [-1.72175808e+01]
 [-1.69628029e+01]
 [-1.69179306e+01]
 [-1.59576159e+01]
 [-1.71386509e+01]
 [-1.89123611e+01]
 [-1.78512897e+01]
 [-1.81882191e+01]
 [-1.92089138e+01]
 [-1.82877464e+01]
 [-1.98154755e+01]
 [-1.87924881e+01]
 [-1.79251385e+01]
 [-1.95466156e+01]
 [-2.00089340e+01]
 [-1.97360878e+01]
 [-1.96157761e+01]
 [-1.99796543e+01]
 [-2.06091061e+01]
 [-1.90839043e+01]
 [-1.98628693e+01]
 [-2.04073162e+01]
 [-2.04490051e+01]
 [-2.05701199e+01]
 [-2.09211178e+01]
 [-2.

In [ ]:
#Parallel model y training
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

from keras.layers import Input, LSTM, Bidirectional, Dense,Dropout
from keras.models import Sequential
from keras.layers import Dense, LSTM, Bidirectional
from keras.optimizers import Adam


input_file = "/content/Scenario1.csv"



x2= pd.read_csv(input_file, usecols=[9,14,17])

y2= pd.read_csv(input_file, usecols=[1])



x2=x2.dropna()
y2=y2.dropna()


x2=x2[:split_index]
y2= y2[:split_index]

scalery = MinMaxScaler(feature_range=(-1,1))
scaler1y = MinMaxScaler(feature_range=(-1,1))
x2 = scalery.fit_transform(x2)
y2 = scaler1y.fit_transform(y2)












x2= np.reshape(x2, (x2.shape[0], x2.shape[1], 1))

# Build the bidirectional LSTM model
modely = Sequential()
modely.add(Bidirectional(LSTM(128, return_sequences=True), input_shape=(x2.shape[1], 1)))
modely.add(Dropout(0.1))

modely.add(Bidirectional(LSTM(64, return_sequences=False)))

modely.add(Dense(25, activation='relu'))  # Add a dense layer with ReLU activation
modely.add(Dense(y2.shape[1]))  # Output layer

# Compile the model
modely.compile(optimizer='adam', loss='mean_squared_error')


# Train the model
modely.fit(x2, y2, batch_size=1, epochs=10)



Epoch 1/10
989/989 [==============================] - 19s 12ms/step - loss: 0.0201
Epoch 2/10
989/989 [==============================] - 12s 12ms/step - loss: 0.0075
Epoch 3/10
989/989 [==============================] - 12s 12ms/step - loss: 0.0061
Epoch 4/10
989/989 [==============================] - 12s 12ms/step - loss: 0.0056
Epoch 5/10
989/989 [==============================] - 12s 12ms/step - loss: 0.0057
Epoch 6/10
989/989 [==============================] - 12s 12ms/step - loss: 0.0054
Epoch 7/10
989/989 [==============================] - 12s 12ms/step - loss: 0.0049
Epoch 8/10
989/989 [==============================] - 12s 13ms/step - loss: 0.0044
Epoch 9/10
989/989 [==============================] - 12s 12ms/step - loss: 0.0051
Epoch 10/10
31/31 [==============================] - 2s 7ms/step
[[-5.44683981e+00]
 [-5.59457064e+00]
 [-6.55270243e+00]
 [-6.42484379e+00]
 [-6.30085945e+00]
 [-4.92035961e+00]
 [-4.85032511e+00]
 [-5.41618729e+00]
 [-5.55982447e+00]
 [-5.02933836e+00

In [ ]:
#Parallel model y prediction
input_file1 = "/content/XF.csv"
xfy= pd.read_csv(input_file1, usecols=[0,2,5])


xfy=scalery.transform(xfy)
xfy= np.reshape(xfy, (xfy.shape[0], xfy.shape[1], 1))


predictionsy = modely.predict(xfy)

# Inverse transform the predictions
predictionsy = scaler1y.inverse_transform(predictionsy)

# Display predictions
print(predictionsy)

31/31 [==============================] - 0s 7ms/step
[[ 9.39520798e+01]
 [ 9.17208252e+01]
 [ 9.38746262e+01]
 [ 9.08064270e+01]
 [ 9.20995483e+01]
 [ 9.05068817e+01]
 [ 9.29685898e+01]
 [ 9.30700073e+01]
 [ 8.59640808e+01]
 [ 9.29852676e+01]
 [ 9.33944092e+01]
 [ 9.17763596e+01]
 [ 9.20113678e+01]
 [ 9.29687195e+01]
 [ 9.19373169e+01]
 [ 9.32740097e+01]
 [ 9.03135452e+01]
 [ 9.01471252e+01]
 [ 9.24970016e+01]
 [ 9.12766342e+01]
 [ 9.23849182e+01]
 [ 8.73066330e+01]
 [ 9.21676331e+01]
 [ 9.09312057e+01]
 [ 9.11136093e+01]
 [ 9.19645233e+01]
 [ 8.84207458e+01]
 [ 9.05171967e+01]
 [ 9.11572113e+01]
 [ 9.10544357e+01]
 [ 9.13436127e+01]
 [ 9.06276398e+01]
 [ 9.01749878e+01]
 [ 9.09859314e+01]
 [ 9.07426071e+01]
 [ 9.09302826e+01]
 [ 8.88721466e+01]
 [ 8.94768829e+01]
 [ 8.99546280e+01]
 [ 9.01965256e+01]
 [ 8.92974091e+01]
 [ 9.13024902e+01]
 [ 8.90948715e+01]
 [ 8.99649506e+01]
 [ 9.03529816e+01]
 [ 8.99107590e+01]
 [ 8.96927872e+01]
 [ 8.94095078e+01]
 [ 8.91740494e+01]
 [ 8.96573486e+0

In [ ]:
#Parallel model z training
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

from keras.layers import Input, LSTM, Bidirectional, Dense,Dropout
from keras.models import Sequential
from keras.layers import Dense, LSTM, Bidirectional
from keras.optimizers import Adam

input_file = "/content/Scenario1.csv"




x3= pd.read_csv(input_file, usecols=[9,15,18])

y3= pd.read_csv(input_file, usecols=[19])


x3=x3.dropna()
y3=y3.dropna()
x3=x3[:split_index]
y3= y3[:split_index]


#scaler = StandardScaler()
scalerz = MinMaxScaler(feature_range=(-1,1))
scaler1z = MinMaxScaler(feature_range=(-1,1))
x3 = scalerz.fit_transform(x3)
y3 = scaler1z.fit_transform(y3)


x3= np.reshape(x3, (x3.shape[0], x3.shape[1], 1))




# Build the bidirectional LSTM model
modelz = Sequential()
modelz.add(Bidirectional(LSTM(128, return_sequences=True), input_shape=(x3.shape[1], 1)))
modelz.add(Dropout(0.1))
modelz.add(Bidirectional(LSTM(64, return_sequences=False)))

modelz.add(Dense(25, activation='relu'))  # Add a dense layer with ReLU activation
modelz.add(Dense(y3.shape[1]))  # Output layer

# Compile the model
modelz.compile(optimizer='adam', loss='mean_squared_error')


# Train the model

modelz.fit(x3, y3, batch_size=1, epochs=10)



Epoch 1/10
989/989 [==============================] - 22s 13ms/step - loss: 0.0691
Epoch 2/10
989/989 [==============================] - 14s 14ms/step - loss: 0.0602
Epoch 3/10
989/989 [==============================] - 13s 13ms/step - loss: 0.0593
Epoch 4/10
989/989 [==============================] - 13s 14ms/step - loss: 0.0575
Epoch 5/10
989/989 [==============================] - 14s 14ms/step - loss: 0.0518
Epoch 6/10
989/989 [==============================] - 13s 13ms/step - loss: 0.0520
Epoch 7/10
989/989 [==============================] - 12s 13ms/step - loss: 0.0503
Epoch 8/10
989/989 [==============================] - 12s 13ms/step - loss: 0.0465
Epoch 9/10
989/989 [==============================] - 12s 12ms/step - loss: 0.0448
Epoch 10/10
31/31 [==============================] - 3s 14ms/step
[[1.9038286]
 [1.6827847]
 [1.7324208]
 [1.789788 ]
 [1.6963696]
 [2.0698445]
 [1.7503543]
 [1.8079554]
 [2.077142 ]
 [1.8587569]
 [1.6858314]
 [1.8045496]
 [1.8274171]
 [1.8826528]
 [1.8

In [ ]:
#Parallel model z prediction

input_file1 = "/content/XF.csv"

xfz= pd.read_csv(input_file1, usecols=[0,3,6])

xfz=xfz[:split_index]


xfz=scalerz.transform(xfz)
xfz= np.reshape(xfz, (xfz.shape[0], xfz.shape[1], 1))


predictionsz = modelz.predict(xfz)

# Inverse transform the predictions
predictionsz = scaler1z.inverse_transform(predictionsz)

# Display predictions
print(predictionsz)

31/31 [==============================] - 0s 8ms/step
[[2.8940058]
 [2.8730602]
 [2.896916 ]
 [2.8845415]
 [2.905119 ]
 [2.8933854]
 [2.9035387]
 [2.883378 ]
 [2.9363067]
 [2.9061637]
 [2.9051366]
 [2.8915896]
 [2.908074 ]
 [2.9603372]
 [2.8974025]
 [2.911674 ]
 [2.9160595]
 [2.9053805]
 [2.982185 ]
 [2.89226  ]
 [2.906554 ]
 [2.9420304]
 [2.926142 ]
 [2.9999654]
 [2.8920457]
 [2.94002  ]
 [2.9225132]
 [2.9484367]
 [2.9189994]
 [2.927536 ]
 [2.9007766]
 [2.8875558]
 [2.9300392]
 [2.9388158]
 [2.9242823]
 [2.9408154]
 [2.9223628]
 [2.941928 ]
 [2.9375825]
 [2.9297593]
 [2.9142828]
 [2.9167104]
 [3.0090232]
 [2.929374 ]
 [2.9443314]
 [2.943476 ]
 [2.9841964]
 [2.9342997]
 [2.940818 ]
 [2.9201024]
 [2.9384403]
 [2.91756  ]
 [2.9515076]
 [2.9412808]
 [2.915452 ]
 [2.949338 ]
 [2.9254417]
 [2.9115348]
 [2.9667819]
 [2.965386 ]
 [2.9631038]
 [2.9700048]
 [3.0846832]
 [2.954405 ]
 [2.97958  ]
 [2.964057 ]
 [2.97517  ]
 [2.9600399]
 [2.9503314]
 [2.9629025]
 [2.9745593]
 [2.9657938]
 [2.9510775

In [ ]:


# Create a DataFrame from the predictions
#df1 = pd.DataFrame(predictions, columns=['x1', 'y1'])
df1 = pd.DataFrame(predictionsx, columns=['x1'])
df1['y1']=predictionsy
df1['z1']=predictionsz

#df = pd.DataFrame(predictions, columns=['Latitude'])

# Save the DataFrame to a CSV file
df1.to_csv('predictions_parallel.csv', index=False)

#split_index = int(0.83 * len(x))

df2 = pd.DataFrame(scaler1.inverse_transform(y),columns=['x2', 'y2','z2'])

# Save the DataFrame to a CSV file
df2.to_csv('actual.csv', index=False)